### ISSUE TITLE
lcui crashes when started

### ISSUE THREAD

**Issue by minego** [kharyam/litra-driver#16]
`❯ lcui
Traceback (most recent call last):
  File "/home/m/.local/bin/lcui", line 8, in <module>
    sys.exit(main())
  File "/home/m/.local/lib/python3.10/site-packages/llgd/ui/__main__.py", line 40, in main
    profile_layout = [sg.Combo(config.get_profile_names(), key='profiles',
  File "/home/m/.local/lib/python3.10/site-packages/llgd/config/llgd_config.py", line 113, in get_profile_names
    profiles.remove(self.CURRENT_PROFILE_NAME)
ValueError: list.remove(x): x not in list
`

**Comment by kharyam** [comment]
@minego Thanks for the find - will take a look

**Comment by kharyam** [comment]
@minego Just published a new release to pypi, this should be fixed.

**Comment by minego** [comment]
Thank you, I'll try it as soon as I'm back at that PC. I appreciate the quick response!
