### ISSUE TITLE
Unable to start lcui, after perform a quick install.

### ISSUE THREAD

**Issue by novahazard** [kharyam/litra-driver#27]
I ran thru the Quick start process and ran into the following error:

```
[jb@thehat ~]$ lcui
Traceback (most recent call last):
  File "/home/jb/.local/bin/lcui", line 5, in <module>
    from llgd.ui.__main__ import main
  File "/home/jb/.local/lib/python3.11/site-packages/llgd/ui/__main__.py", line 4, in <module>
    import PySimpleGUI as sg  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jb/.local/lib/python3.11/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/home/jb/.local/lib/python3.11/site-packages/PySimpleGUI/PySimpleGUI.py", line 136, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```
Tried to do a:

`pip install tk` 

Then tried to run `lcui` and got the following error:

```
jb@thehat ~]$ pip install tk
Defaulting to user installation because normal site-packages is not writeable
Collecting tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
Installing collected packages: tk
Successfully installed tk-0.1.0
[jb@thehat ~]$ lcui
Traceback (most recent call last):
  File "/home/jb/.local/bin/lcui", line 5, in <module>
    from llgd.ui.__main__ import main
  File "/home/jb/.local/lib/python3.11/site-packages/llgd/ui/__main__.py", line 4, in <module>
    import PySimpleGUI as sg  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jb/.local/lib/python3.11/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/home/jb/.local/lib/python3.11/site-packages/PySimpleGUI/PySimpleGUI.py", line 136, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```
On my latest attempt I ran `sudo dnf install python3-tkinter` and then tried `lcui` and got the following:

```
jb@thehat ~]$ sudo dnf install python3-tkinter
[sudo] password for jb: 
Last metadata expiration check: 3:45:05 ago on Tue 10 Jan 2023 12:30:50 PM EST.
Dependencies resolved.
================================================================================================================================================================
 Package                                    Architecture                      Version                                  Repository                          Size
================================================================================================================================================================
Installing:
 python3-tkinter                            x86_64                            3.11.1-1.fc37                            updates                            417 k

Transaction Summary
================================================================================================================================================================
Install  1 Package

Total download size: 417 k
Installed size: 2.3 M
Is this ok [y/N]: y
Downloading Packages:
python3-tkinter-3.11.1-1.fc37.x86_64.rpm                                                                                        1.5 MB/s | 417 kB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                           602 kB/s | 417 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                        1/1 
  Installing       : python3-tkinter-3.11.1-1.fc37.x86_64                                                                                                   1/1 
  Running scriptlet: python3-tkinter-3.11.1-1.fc37.x86_64                                                                                                   1/1 
  Verifying        : python3-tkinter-3.11.1-1.fc37.x86_64                                                                                                   1/1 

Installed:
  python3-tkinter-3.11.1-1.fc37.x86_64                                                                                                                          

Complete!
[jb@thehat ~]$ lcui
Traceback (most recent call last):
  File "/home/jb/.local/bin/lcui", line 5, in <module>
    from llgd.ui.__main__ import main
  File "/home/jb/.local/lib/python3.11/site-packages/llgd/ui/__main__.py", line 5, in <module>
    from psgtray import SystemTray  # pylint: disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jb/.local/lib/python3.11/site-packages/psgtray/__init__.py", line 2, in <module>
    from .psgtray import *
  File "/home/jb/.local/lib/python3.11/site-packages/psgtray/psgtray.py", line 1, in <module>
    import pystray, io, base64, threading, time
  File "/home/jb/.local/lib/python3.11/site-packages/pystray/__init__.py", line 48, in <module>
    Icon = backend().Icon
           ^^^^^^^^^
  File "/home/jb/.local/lib/python3.11/site-packages/pystray/__init__.py", line 40, in backend
    return importlib.import_module(__package__ + '._' + module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jb/.local/lib/python3.11/site-packages/pystray/_appindicator.py", line 22, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

Currently running Fedora 37, Workstation Edition, 64-bit.

Any thoughts?

**Comment by kharyam** [comment]
Thanks! I was able to recreate this issue on a Fedora 37 virtual machine and will update the readme with a couple of dependencies.  Give this  a try:

```
sudo dnf install -y python3-tkinter libappindicator-gtk3
```
