### ISSUE TITLE
Unable to use cli - The device has no langid

### ISSUE THREAD

**Issue by kalenmike** [kharyam/litra-driver#32]
I am unable to get the cli to start.

System info:

> Ubuntu 22.04.3 LTS
> i3 4.22
> Bus 001 Device 007: ID 046d:c900 Logitech, Inc. Litra Glow

Steps to reproduce:

```
pip install litra-driver

sudo tee /etc/udev/rules.d/82-litra-glow.rules <<< 'SUBSYSTEM=="usb", ATTR{idVendor}=="046d", ATTR{idProduct}=="c900",MODE="0666"'
sudo tee /etc/udev/rules.d/82-litra-beam.rules <<< 'SUBSYSTEM=="usb", ATTR{idVendor}=="046d", ATTR{idProduct}=="c901",MODE="0666"'

lc --help
```

```
Traceback (most recent call last):
  File "/home/ace/.local/bin/lc", line 5, in <module>
    from llgd.cli.cli import main
  File "/home/ace/.local/lib/python3.10/site-packages/llgd/cli/cli.py", line 8, in <module>
    from llgd.lib.llgd_lib import light_on, light_off, set_brightness, set_temperature
  File "/home/ace/.local/lib/python3.10/site-packages/llgd/lib/llgd_lib.py", line 153, in <module>
    find_devices()
  File "/home/ace/.local/lib/python3.10/site-packages/llgd/lib/llgd_lib.py", line 41, in find_devices
    logging.info('Found Device "%s"', product_device.product)
  File "/home/ace/.local/lib/python3.10/site-packages/usb/core.py", line 875, in product
    self._product = util.get_string(self, self.iProduct)
  File "/home/ace/.local/lib/python3.10/site-packages/usb/util.py", line 313, in get_string
    raise ValueError("The device has no langid"
ValueError: The device has no langid (permission issue, no string descriptors supported or device error)
```

**Comment by gabeguz** [comment]
I needed to reboot before it worked for me, I was getting the same error.

**Comment by sethforprivacy** [comment]
After [installing the udev rules](https://github.com/kharyam/litra-driver#linux) you can usually just unplug/re-plug the device into your computer to activate them -- that's what worked for me as it does with most udev rule issues.

**Comment by kharyam** [comment]
Just a heads up that I've released a [go version of this application ](https://github.com/kharyam/go-litra-driver), a single native executable for the cli and ui.  Let me know if you can give it a try!
